kind: Service
apiVersion: v1
metadata:
  name: cleanstreet-service
spec:
  selector:
    app: cleanstreet-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanstreet
  labels:
    app: cleanstreet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleanstreet-service
  template:
    metadata:
      labels:
        app: cleanstreet-service
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: cleanstreet-service
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
